buildscript {
  repositories {
    maven { url 'https://maven.myket.ir/' }
  }
}
allprojects {
  repositories {
    maven { url 'https://maven.myket.ir/' }
  }
}

rootProject.buildDir = "../build"
subprojects {
    project.buildDir = "${rootProject.buildDir}/${project.name}"
}

tasks.register("clean", Delete) {
    delete rootProject.buildDir
}


subprojects { subproject ->
    subproject.plugins.withId("com.android.application") {
        subproject.android.buildToolsVersion = "37.0.0"
    }

    subproject.plugins.withId("com.android.library") {
        subproject.android.buildToolsVersion = "37.0.0"
    }
}